Document: vhostmanage
Title: Debian vhostmanage Manual
Author: <insert document author here>
Abstract: This manual describes what vhostmanage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vhostmanage/vhostmanage.sgml.gz

Format: postscript
Files: /usr/share/doc/vhostmanage/vhostmanage.ps.gz

Format: text
Files: /usr/share/doc/vhostmanage/vhostmanage.text.gz

Format: HTML
Index: /usr/share/doc/vhostmanage/html/index.html
Files: /usr/share/doc/vhostmanage/html/*.html
